# Protocol / Document sharing template for Jekyll which works with Github Pages

organisation: Harrogate MSK Radiology
title: MRI Scanning Protocols
email: your-email@example.com
description: Open source MRI scan protocols by [Harrogate Hospital](https://hdft.nhs.uk/) Department of Musculoskeletal Radiology.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yorkshirerad
github_username:  danfascia
timezone: GMT

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown

permalink: pretty
sass: 
  style: compressed
  sass_dir: _sass

collections:
  posts:
    title: Posts
    output: true
  pages:
    title: Pages
    output: true
  protocols:
    title: Protocols
    output: true

# Directory settings, you can choose which folder collection supplies the articles on the front page and which YAML frontmatter they are taxonomised by
featured-collection: protocols
taxonomy: body_part

defaults:
  #Protocols
  - scope:
      path: ""
      type: protocols
    values:
      layout: protocol
