# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
organisation: Harrogate MSK Radiology
title: MRI Scanning Protocols
email: your-email@example.com
description: > Open Source MRI scan protocols as used in [Harrogate District Hospital Foundation NHS Trust](https://hdft.nhs.uk), Yorkshire. Free to use, modify and share as you please.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yorkshirerad
github_username:  danfascia

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown

permalink: pretty
sass: 
  style: compressed
  sass_dir: _sass

collections:
  posts:
    title: Posts
    output: true
  pages:
    title: Pages
    output: true
  protocols:
    title: Protocols
    output: true


defaults:
  #Protocols
  - scope:
      path: ""
      type: protocols
    values:
      layout: protocol

primary_color: #2C75DC
