backend:
  name: github
  repo: harrogatemsk/harrogatemsk.github.io
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "Protocols"
    label: "Protocol"
    folder: "_protocols"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "protocol"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body Part", name: "body_part", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Content", name: "content", widget: "markdown"}
